global:
  useNetworkPolicies: true
  # nodeSelector: Node labels for pod assignment
  nodeSelector: []
  # tolerations: tolerations for pod assignment
  tolerations: []
  # nodeSelector: Node labels for pod assignment of stateful sets (database)
  nodeSelectorSts: []
  # tolerationsSts: tolerations for pod assignment of stateful sets (database)

useDefaultDenyNetworkPolicy: false

broker:
  monitoring:
    metricsEnabled: true
    podMonitorEnabled: true
  service:
    type: ClusterIP
  networkPolicy:
    ingress: []
    extraIngress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
        ports:
        - port: 80
          protocol: TCP

jobSpawner:
  workerNetworkPolicy:
    extraEgress: []

mongodb:
  persistence:
    storageClassName: gp2

postgresql:
  persistence:
    storageClassName: gp2
  database: "test-db"
  database_user: "postgres"

rabbitmq:
  persistence:
    storageClassName: gp2
