global:
  useNetworkPolicies: true
  # nodeSelector: Node labels for pod assignment
  nodeSelector: []
  # tolerations: tolerations for pod assignment
  tolerations: []
  # nodeSelector: Node labels for pod assignment of stateful sets (database)
  nodeSelectorSts: []
  # tolerationsSts: tolerations for pod assignment of stateful sets (database)


# reduced resources for lower demand env or for testing purposes:

broker:
  uwsgi:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 512Mi

postgresql:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

mongodb:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

rabbitmq:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
