#!/bin/sh

if [ -z "${CONNECTION_STRING}" ]; then
    cat << EOF | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"
    CREATE USER broker WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_BROKER_PWD}';
    CREATE USER worker WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_WORKER_PWD}';
    CREATE USER cleaner WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_CLEANER_PWD}';
    CREATE USER dep_check WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_DEPENDENCY_CHECK_PWD}';
    CREATE USER job_spawner WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_SPWN_PWD}';
    CREATE USER event_manager WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_EVENT_MANAGER_PWD}';
    CREATE USER k8s_job_canceler WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_K8S_CANCEL_PWD}';
    CREATE USER k8s_job_watcher WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_K8S_JOB_WATCHER_PWD}';
EOF
    cat /docker-entrypoint-initdb.d/create_tables_and_set_permissions | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"
else
    cat << EOF | psql -v ON_ERROR_STOP=1 "${CONNECTION_STRING}"
    CREATE USER broker WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_BROKER_PWD}';
    CREATE USER worker WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_WORKER_PWD}';
    CREATE USER cleaner WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_CLEANER_PWD}';
    CREATE USER dep_check WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_DEPENDENCY_CHECK_PWD}';
    CREATE USER job_spawner WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_SPWN_PWD}';
    CREATE USER event_manager WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_EVENT_MANAGER_PWD}';
    CREATE USER k8s_job_canceler WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_K8S_CANCEL_PWD}';
    CREATE USER k8s_job_watcher WITH LOGIN PASSWORD '${GMS_RUNNER_DATABASE_K8S_JOB_WATCHER_PWD}';
EOF
    cat /docker-entrypoint-initdb.d/create_tables_and_set_permissions | psql -v ON_ERROR_STOP=1  "${CONNECTION_STRING}"
fi
