{{ if .Values.global.useNetworkPolicies }}
{{ if .Values.global.useDefaultDenyNetworkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}-default-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{ end }}
{{ end }}
