{{ if .Values.global.useNetworkPolicies }}
{{ if .Values.useDefaultDenyNetworkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gams-engine.prefixname" . }}-deny-all-np
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{ end }}
{{ end }}
