{{ if .Values.global.useNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gams-engine.prefixname" . }}-fwd-prxy-np
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "gams-engine.prefixname" . }}-fwd-prxy
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "gams-engine.prefixname" . }}-mongo
      ports:
        - protocol: TCP
          port: 27017
    {{- if .Values.forwardProxy.networkPolicy.extraEgress }}
    # Optional extra egress rules
    {{- include "common.tplvalues.render" (dict "value" .Values.forwardProxy.networkPolicy.extraEgress "context" $) | nindent 4 }}
    {{- end }}
  ingress:
    {{- if .Values.forwardProxy.networkPolicy.extraIngress }}
    # Optional extra ingress rules
    {{- include "common.tplvalues.render" (dict "value" .Values.forwardProxy.networkPolicy.extraIngress "context" $) | nindent 4 }}
    {{- end }}
    - from:
      - podSelector:
          matchLabels:
            app: {{ include "gams-engine.prefixname" . }}-broker
      ports:
        - protocol: TCP
          port: 8000
{{ end }}
