apiVersion: v1
kind: Service
metadata:
  name: forward-proxy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: forward-proxy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
