{{ if .Values.global.useNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}-hypercube-unpacker
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "common.names.fullname" . }}-hypercube-unpacker
  policyTypes:
    - Egress
    - Ingress
  ingress: []
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "common.names.fullname" . }}-queue
      ports:
        - protocol: TCP
          port: 5672
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{ end }}
