{{ if .Values.global.useNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gams-engine.prefixname" . }}-hc-unp-np
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "gams-engine.prefixname" . }}-hc-unp
  policyTypes:
    - Egress
    - Ingress
  ingress: []
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "gams-engine.prefixname" . }}-queue
      ports:
        - protocol: TCP
          port: 5672
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{ end }}
