{{ if .Values.global.useNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}-job-spawner
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "common.names.fullname" . }}-job-spawner
  policyTypes:
    - Egress
    - Ingress
  ingress: []
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "common.names.fullname" . }}-queue
      ports:
        - protocol: TCP
          port: 5672
{{- if .Values.postgresql.externalDatabase.enabled }}
    - to:
      - podSelector:
{{ toYaml .Values.postgresql.externalDatabase.networkPolicy.podSelector | indent 10 }}
        namespaceSelector:
{{ toYaml .Values.postgresql.externalDatabase.networkPolicy.namespaceSelector | indent 10 }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgresql.externalDatabase.port }}
{{- else }}
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "common.names.fullname" . }}-postgres
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "common.names.fullname" . }}-mongo
      ports:
        - protocol: TCP
          port: 27017
    - to:
      - ipBlock:
          cidr: "0.0.0.0/0"
      ports:
        - protocol: TCP
          port: 6443
        - protocol: TCP
          port: 443
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{ end }}
