kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.mongodb.useCustomStorageClass }}
  storageClassName: "{{ .Values.mongodb.storageClassName }}"
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
