{{ if .Values.useNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pgbouncer-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: pgbouncer
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: worker
      - podSelector:
          matchLabels:
            app: job-watcher
      - podSelector:
          matchLabels:
            app: job-spawner
      - podSelector:
          matchLabels:
            app: job-canceler
      - podSelector:
          matchLabels:
            app: hypercube-appender
      - podSelector:
          matchLabels:
            app: event-manager
      - podSelector:
          matchLabels:
            app: dep-checker
      - podSelector:
          matchLabels:
            app: cleaner
      - podSelector:
          matchLabels:
            app: broker
      ports:
        - protocol: TCP
          port: 6432
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: database
      ports:
        - protocol: TCP
          port: 5432
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{ end }}
