apiVersion: v1
kind: Service
metadata:
  name: database-bouncer
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: 6432
      targetPort: 6432
