{{ if .Values.useNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: worker
      - podSelector:
          matchLabels:
            app: job-watcher
      - podSelector:
          matchLabels:
            app: job-spawner
      - podSelector:
          matchLabels:
            app: job-canceler
      - podSelector:
          matchLabels:
            app: hypercube-appender
      - podSelector:
          matchLabels:
            app: event-manager
      - podSelector:
          matchLabels:
            app: dep-checker
      - podSelector:
          matchLabels:
            app: cleaner
      - podSelector:
          matchLabels:
            app: broker
      - podSelector:
          matchLabels:
            app: pgbouncer
      ports:
        - protocol: TCP
          port: 5432
  egress: []
{{ end }}
