kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-pvc
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.postgresql.useCustomStorageClass }}
  storageClassName: "{{ .Values.postgresql.storageClassName }}"
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
