apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: queue
  serviceName: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
    {{- if .Values.rabbitmq.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.rabbitmq.affinity "context" $) | nindent 8 }}
    {{- end }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: init-queue-definition-data
          image: python:3.13-alpine
          command: ["python3", "/tmp/generate_hashes.py"]
          volumeMounts:
            - name: queue-definition-data
              mountPath: /data_in/definitions.json
              subPath: definitions.json
              readOnly: true
            - name: queue-generate-hashes-code
              mountPath: /tmp/generate_hashes.py
              subPath: generate_hashes.py
            - name: queue-definition-data-templated
              mountPath: /data_out
          env:
            - name: GMS_RUNNER_RABBIT_BROKER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_BROKER_PWD
            - name: GMS_RUNNER_RABBIT_WORKER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_WORKER_PWD
            - name: GMS_RUNNER_RABBIT_HYPERCUBE_APPENDER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_HYPERCUBE_APPENDER_PWD
            - name: GMS_RUNNER_RABBIT_CLEANER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_CLEANER_PWD
            - name: GMS_RUNNER_RABBIT_HYPERCUBE_UNPACKER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_HYPERCUBE_UNPACKER_PWD
            - name: GMS_RUNNER_RABBIT_MIGRATE_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_MIGRATE_PWD
            - name: GMS_RUNNER_RABBIT_SPWN_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_SPWN_PWD
            - name: GMS_RUNNER_RABBIT_DEPENDENCY_CHECK_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_DEPENDENCY_CHECK_PWD
            - name: GMS_RUNNER_RABBIT_EVENT_MANAGER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_EVENT_MANAGER_PWD
            - name: GMS_RUNNER_RABBIT_K8S_CANCEL_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_K8S_CANCEL_PWD
            - name: GMS_RUNNER_RABBIT_K8S_JOB_WATCHER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_K8S_JOB_WATCHER_PWD
      containers:
        - name: gamswebqueue
          image: rabbitmq:3.8.2-management-alpine
          resources:
{{ toYaml .Values.rabbitmq.resources | indent 12 }}
          ports:
            - containerPort: 5672
          volumeMounts:
            - name: queue-data
              mountPath: /var/lib/rabbitmq/mnesia/
            - name: queue-definition-data-templated
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
              readOnly: true
      volumes:
        - name: queue-data
          persistentVolumeClaim:
            claimName: queue-pvc
        - name: queue-definition-data
          configMap:
            name: queue-definition
            items:
              - key: definitions.json
                path: definitions.json
        - name: queue-definition-data-templated
          emptyDir: {}
        - name: queue-generate-hashes-code
          configMap:
            name: queue-generate-hashes
            items:
              - key: generate_hashes.py
                path: generate_hashes.py
