apiVersion: v1
kind: Service
metadata:
  name: queue
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: queue
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  clusterIP: None
