apiVersion: v1
kind: Secret
metadata:
  name: gamsworker
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GMS_RUNNER_DATABASE_ADMIN_PWD: "{{ required "value 'gmsRunnerDatabaseAdminPwd' is required" .Values.gmsRunnerDatabaseAdminPwd }}"
  GMS_RUNNER_DATABASE_BROKER_PWD: "{{ required "value 'gmsRunnerDatabaseBrokerPwd' is required" .Values.gmsRunnerDatabaseBrokerPwd }}"
  GMS_RUNNER_DATABASE_WORKER_PWD: "{{ required "value 'gmsRunnerDatabaseWorkerPwd' is required" .Values.gmsRunnerDatabaseWorkerPwd }}"
  GMS_RUNNER_DATABASE_CLEANER_PWD: "{{ required "value 'gmsRunnerDatabaseCleanerPwd' is required" .Values.gmsRunnerDatabaseCleanerPwd }}"
  GMS_RUNNER_RABBIT_BROKER_PWD: "{{ required "value 'gmsRunnerRabbitBrokerPwd' is required" .Values.gmsRunnerRabbitBrokerPwd }}"
  GMS_RUNNER_RABBIT_WORKER_PWD: "{{ required "value 'gmsRunnerRabbitWorkerPwd' is required" .Values.gmsRunnerRabbitWorkerPwd }}"
  GMS_RUNNER_RABBIT_HYPERCUBE_APPENDER_PWD: "{{ required "value 'gmsRunnerRabbitHypercubeAppenderPwd' is required" .Values.gmsRunnerRabbitHypercubeAppenderPwd }}"
  GMS_RUNNER_RABBIT_CLEANER_PWD: "{{ required "value 'gmsRunnerRabbitCleanerPwd' is required" .Values.gmsRunnerRabbitCleanerPwd }}"
  GMS_RUNNER_RABBIT_HYPERCUBE_UNPACKER_PWD: "{{ required "value 'gmsRunnerRabbitHypercubeUnpackerPwd' is required" .Values.gmsRunnerRabbitHypercubeUnpackerPwd }}"
  GMS_RUNNER_MONGO_BROKER_PWD: "{{ required "value 'gmsRunnerMongoBrokerPwd' is required" .Values.gmsRunnerMongoBrokerPwd }}"
  GMS_RUNNER_MONGO_WORKER_PWD: "{{ required "value 'gmsRunnerMongoWorkerPwd' is required" .Values.gmsRunnerMongoWorkerPwd }}"
  GMS_RUNNER_MONGO_HYPERCUBE_APPENDER_PWD: "{{ required "value 'gmsRunnerMongoHypercubeAppenderPwd' is required" .Values.gmsRunnerMongoHypercubeAppenderPwd }}"
  GMS_RUNNER_MONGO_CLEANER_PWD: "{{ required "value 'gmsRunnerMongoCleanerPwd' is required" .Values.gmsRunnerMongoCleanerPwd }}"
  GMS_RUNNER_RABBIT_MIGRATE_PWD: "{{ required "value 'gmsRunnerRabbitMigratePwd' is required" .Values.gmsRunnerRabbitMigratePwd }}"
  GMS_RUNNER_RABBIT_SPWN_PWD: "{{ required "value 'gmsRunnerRabbitSpwnPwd' is required" .Values.gmsRunnerRabbitSpwnPwd }}"
  GMS_RUNNER_MONGO_SPWN_PWD: "{{ required "value 'gmsRunnerMongoSpwnPwd' is required" .Values.gmsRunnerMongoSpwnPwd }}"
  GMS_RUNNER_DATABASE_SPWN_PWD: "{{ required "value 'gmsRunnerDatabaseSpwnPwd' is required" .Values.gmsRunnerDatabaseSpwnPwd }}"
  GMS_RUNNER_DATABASE_K8S_CANCEL_PWD: "{{ required "value 'gmsRunnerDatabaseK8sCancelPwd' is required" .Values.gmsRunnerDatabaseK8sCancelPwd }}"
  GMS_RUNNER_RABBIT_K8S_CANCEL_PWD: "{{ required "value 'gmsRunnerRabbitK8sCancelPwd' is required" .Values.gmsRunnerRabbitK8sCancelPwd }}"
  GMS_RUNNER_MONGO_K8S_CANCEL_PWD: "{{ required "value 'gmsRunnerMongoK8sCancelPwd' is required" .Values.gmsRunnerMongoK8sCancelPwd }}"
  GMS_RUNNER_RABBIT_DEPENDENCY_CHECK_PWD: "{{ required "value 'gmsRunnerRabbitDependencyCheckPwd' is required" .Values.gmsRunnerRabbitDependencyCheckPwd }}"
  GMS_RUNNER_MONGO_DEPENDENCY_CHECK_PWD: "{{ required "value 'gmsRunnerMongoDependencyCheckPwd' is required" .Values.gmsRunnerMongoDependencyCheckPwd }}"
  GMS_RUNNER_DATABASE_DEPENDENCY_CHECK_PWD: "{{ required "value 'gmsRunnerDatabaseDependencyCheckPwd' is required" .Values.gmsRunnerDatabaseDependencyCheckPwd }}"
  GMS_RUNNER_RABBIT_EVENT_MANAGER_PWD: "{{ required "value 'gmsRunnerDatabaseEventManagerPwd' is required" .Values.gmsRunnerRabbitEventManagerPwd }}"
  GMS_RUNNER_MONGO_EVENT_MANAGER_PWD: "{{ required "value 'gmsRunnerDatabaseEventManagerPwd' is required" .Values.gmsRunnerMongoEventManagerPwd }}"
  GMS_RUNNER_MONGO_FORWARD_PROXY_PWD: "{{ required "value 'gmsRunnerDatabaseEventManagerPwd' is required" .Values.gmsRunnerMongoForwardProxyPwd }}"
  GMS_RUNNER_DATABASE_EVENT_MANAGER_PWD: "{{ required "value 'gmsRunnerDatabaseEventManagerPwd' is required" .Values.gmsRunnerDatabaseEventManagerPwd }}"
  GMS_RUNNER_MONGO_K8S_JOB_WATCHER_PWD: "{{ required "value 'gmsRunnerMongoK8sJobWatcherPwd' is required" .Values.gmsRunnerMongoK8sJobWatcherPwd }}"
  GMS_RUNNER_DATABASE_K8S_JOB_WATCHER_PWD: "{{ required "value 'gmsRunnerDatabaseK8sJobWatcherPwd' is required" .Values.gmsRunnerDatabaseK8sJobWatcherPwd }}"
  GMS_RUNNER_RABBIT_K8S_JOB_WATCHER_PWD:  "{{ required "value 'gmsRunnerRabbitK8sJobWatcherPwd' is required" .Values.gmsRunnerRabbitK8sJobWatcherPwd }}"
  GMS_RUNNER_FORWARD_PROXY_PWD:  "{{ required "value 'gmsRunnerForwardProxyPwd' is required" .Values.gmsRunnerForwardProxyPwd }}"
  GMS_RUNNER_FORWARD_PROXY_SECRET:  "{{ required "value 'gmsRunnerForwardProxySecret' is required" .Values.gmsRunnerForwardProxySecret }}"
  GMS_RUNNER_FORWARD_PROXY_ENC_KEY:  "{{ required "value 'gmsRunnerForwardProxyEncKey' is required" .Values.gmsRunnerForwardProxyEncKey }}"
  GMS_RUNNER_PGBOUNCER_USERLIST: '"broker" "{{ .Values.gmsRunnerDatabaseBrokerPwd }}"'
