{{ if .Values.global.useNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gams-engine.name" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: worker
  policyTypes:
    - Egress
    - Ingress
  ingress: []
  egress:
    {{- if .Values.jobSpawner.workerNetworkPolicy.extraEgress }}
    # Optional extra egress rules
    {{- include "common.tplvalues.render" (dict "value" .Values.jobSpawner.workerNetworkPolicy.extraEgress "context" $) | nindent 4 }}
    {{- end }}
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "gams-engine.name" . }}-queue
      ports:
        - protocol: TCP
          port: 5672
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "gams-engine.name" . }}-pgbouncer
      ports:
        - protocol: TCP
          port: 6432
    - to:
      - podSelector:
          matchLabels:
            app: {{ include "gams-engine.name" . }}-mongo
      ports:
        - protocol: TCP
          port: 27017
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{ end }}
